### ISSUE TITLE
Can't read input file

### ISSUE THREAD

**Issue by exmex** [ProjectBots/StreamRaidersBot#11]
> IIOException at Line: -1
javax.imageio.IIOException: Can't read input file!
        at java.desktop/javax.imageio.ImageIO.read(Unknown Source)
        at include.GUI.setImage(GUI.java:1550)
        at program.Run.raids(Run.java:420)
        at program.Run.runs(Run.java:158)
        at program.Run$4.run(Run.java:292)
        at java.base/java.util.TimerThread.mainLoop(Unknown Source)
        at java.base/java.util.TimerThread.run(Unknown Source)

This only happens on one of my 2 accounts

**Comment by ProjectBots** [comment]
Does this happen directly on the start or only when you run the profile?
Can you please check if you got a file named nochest.png under data/ChestPics/ ?
Maybe try to manually switch all raids your currently in on your browser.
I will look over this when I’m home

**Comment by exmex** [comment]
Did had data/ChestPics for some reason
