### ISSUE TITLE
Store refresh error

### ISSUE THREAD

**Issue by rayzynx** [ProjectBots/StreamRaidersBot#17]
If you used the store refresh while playing manually and then went to turn the bot on it spits this error out on a loop:

---- 15:6,45 ----
critical error happened for bob at "store" -> skipped this round
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonPrimitive.getAsBoolean()" because the return value of "com.google.gson.JsonObject.getAsJsonPrimitive(String)" is null
	at program.Run.store(Run.java:356)
	at program.Run.runs(Run.java:173)
	at program.Run$4.run(Run.java:290)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

I've circumvented it in the mean time by disabling all purchase options in the settings.

**Comment by ProjectBots** [comment]
I'll look into this.
The loop is because the bot reloads when an error occurred and tries it again

**Comment by ProjectBots** [comment]
new debug version is released [v5.0.2debug](https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v5.0.2debug)

**Comment by rayzynx** [comment]
Is the new debug version I've encountered no errors or issues. I've deliberately (manually) purchased a store re-supply while it's running and it handled it fine - Buying scrolls that it could afford and continuing to fight as per normal.

**Comment by ProjectBots** [comment]
👍🏻 i will make it a full release this weekend as soon as i updated the guide

**Comment by rayzynx** [comment]
An update on this issue, this is with the new 5.0.2 debug. I believe it was caused again by a manual store refresh but it beats me - this is what was in the log.app (it did not loop - it just stopped entirely and froze at 0 seconds).

---- 5:7,0 ----
critical error happened for bob at "captains" -> skipped this round
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1697)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1404)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at include.Http.sendUrlEncoded(Http.java:117)
	at program.SRR.sendPost(SRR.java:136)
	at program.SRR.getCaptainsForSearch(SRR.java:265)
	at program.SRRHelper.search(SRRHelper.java:240)
	at program.Run.getCaps(Run.java:659)
	at program.Run.captains(Run.java:629)
	at program.Run.runs(Run.java:156)
	at program.Run$4.run(Run.java:289)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1498)
	... 25 more
