### ISSUE TITLE
An update on this issue, this is with the new 5.0.2 debug. I believe it was caused again by a manual store refresh but it beats me - this is what was in the log.app (it did not loop - it just stopped entirely and froze at 0 seconds).

### ISSUE THREAD

**Issue by ProjectBots** [ProjectBots/StreamRaidersBot#18]
An update on this issue, this is with the new 5.0.2 debug. I believe it was caused again by a manual store refresh but it beats me - this is what was in the log.app (it did not loop - it just stopped entirely and froze at 0 seconds).

---- 5:7,0 ----
critical error happened for bob at "captains" -> skipped this round
javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1697)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1404)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at include.Http.sendUrlEncoded(Http.java:117)
	at program.SRR.sendPost(SRR.java:136)
	at program.SRR.getCaptainsForSearch(SRR.java:265)
	at program.SRRHelper.search(SRRHelper.java:240)
	at program.Run.getCaps(Run.java:659)
	at program.Run.captains(Run.java:629)
	at program.Run.runs(Run.java:156)
	at program.Run$4.run(Run.java:289)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1498)
	... 25 more

_Originally posted by @rayzynx in https://github.com/ProjectBots/StreamRaidersBot/issues/17#issuecomment-834054112_

**Comment by ProjectBots** [comment]
This is an exception which can be thrown if the internet connection failed during a request. Did the button turned red like intended?

**Comment by rayzynx** [comment]
I was active on the device. It did not turn red and the internet was functioning fine for other applications.

**Comment by ProjectBots** [comment]
Maybe an update from StreamRaiders changed something in the post requests

**Comment by rayzynx** [comment]
I've re-downloaded the debug version (just in case) and re-entered the account / created new profile etc. So far no errors popped up after an hour and a few minutes of running it. Nothing in the powershell window nor any logs.app file was created.
