### ISSUE TITLE
critical error

### ISSUE THREAD

**Issue by Geeps38** [ProjectBots/StreamRaidersBot#32]
I keep getting critical errors. This is from the log

critical error happened for Geeps at "Geeps captains" -> skipped this round
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.getAsJsonPrimitive(String)" because the return value of "com.google.gson.JsonObject.getAsJsonObject(String)" is null
	at program.Configs.getChestBoolean(Configs.java:192)
	at program.Run.captains(Run.java:806)
	at program.Run.runs(Run.java:174)
	at program.Run$2.run(Run.java:103)
	at java.base/java.lang.Thread.run(Thread.java:831)

Is there anything I can do to fix this issue?

**Comment by ProjectBots** [comment]
Please check if you’re running the newest version
