### ISSUE TITLE
Unable to launch in Linux

### ISSUE THREAD

**Issue by Lutzy** [ProjectBots/StreamRaidersBot#34]
Cloned the project, switched to the 6.3.4beta tag, using jdk16, ran mvn clean install then java -jar target/StreamRaidersBot-6.3.4.jar

```
java -jar target/StreamRaidersBot-6.3.4.jar 

        ███████╗██████╗     ██████╗  ██████╗ ████████╗
        ██╔════╝██╔══██╗    ██╔══██╗██╔═══██╗╚══██╔══╝
        ███████╗██████╔╝    ██████╔╝██║   ██║   ██║   
        ╚════██║██╔══██╗    ██╔══██╗██║   ██║   ██║   
        ███████║██║  ██║    ██████╔╝╚██████╔╝   ██║   
        ╚══════╝╚═╝  ╚═╝    ╚═════╝  ╚═════╝    ╚═╝   


by ProjectBots https://github.com/ProjectBots/StreamRaiderBot
Version: 6.3.4beta

Uncaught error fetching image:
java.lang.NullPointerException: Cannot invoke "java.net.URL.openConnection()" because "this.url" is null
        at java.desktop/sun.awt.image.URLImageSource.getConnection(URLImageSource.java:101)
        at java.desktop/sun.awt.image.URLImageSource.getDecoder(URLImageSource.java:111)
        at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:263)
        at java.desktop/sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:212)
        at java.desktop/sun.awt.image.ImageFetcher.run(ImageFetcher.java:176)

```

**Comment by ProjectBots** [comment]
Run it without the target/
Java -jar StreamRaidersBot.jar

**Comment by Lutzy** [comment]
```
ls
cef_bundle  changelog.json  data  pom.xml  src  target
```

**Comment by ProjectBots** [comment]
It cant get the images in the data folder therefore it’s in the wrong location. Try putting it in the same folder as the jar and run it there. Java -jar StreamRaidersBot.jar

**Comment by Lutzy** [comment]
Thanks, some tinkering got it going
