### ISSUE TITLE
Error and bot won't work?

### ISSUE THREAD

**Issue by derpyderpaderp** [ProjectBots/StreamRaidersBot#40]
I keep getting this error over and over 

---- 17:47,22 ----
Configs -> getChestBoolean: err=NullPointer cType=odysseychest
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.getAsJsonPrimitive(String)" because the return value of "com.google.gson.JsonObject.getAsJsonObject(String)" is null
	at program.Configs.getChestBoolean(Configs.java:196)
	at program.Run.captains(Run.java:857)
	at program.Run.runs(Run.java:175)
	at program.Run$4.run(Run.java:331)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by ProjectBots** [comment]
fixed in [v6.3.7](https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v6.3.7beta)
