### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CiderSpy** [ProjectBots/StreamRaidersBot#41]
Configs -> getChestBoolean: err=NullPointer cType=icefallchest
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.getAsJsonPrimitive(String)" because the return value of "com.google.gson.JsonObject.getAsJsonObject(String)" is null
	at program.Configs.getChestBoolean(Configs.java:196)
	at program.Run.captains(Run.java:854)
	at program.Run.runs(Run.java:174)
	at program.Run$2.run(Run.java:103)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by ProjectBots** [comment]
fixed in [v6.3.8beta](https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v6.3.8beta)

**Comment by CiderSpy** [comment]
Your the best !

________________________________
