### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TrulliBalboa** [ProjectBots/StreamRaidersBot#42]
Run -> captains: err=No Captain Matches
program.Run$NoCapMatchException: No Captain Matches
	at program.Run.getCaps(Run.java:924)
	at program.Run.getCaps(Run.java:914)
	at program.Run.captains(Run.java:868)
	at program.Run.runs(Run.java:175)
	at program.Run$4.run(Run.java:331)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by ProjectBots** [comment]
Dungeons is over. You have to set the dungeon slot to none

**Comment by TrulliBalboa** [comment]
Oh, damn, Im an idiot. Thank you.
