### ISSUE TITLE
error on captain mode

### ISSUE THREAD

**Issue by sioffi** [ProjectBots/StreamRaidersBot#43]
here my log

(Captain): Run -> setRunning
java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonArray (com.google.gson.JsonNull and com.google.gson.JsonArray are in unnamed module of loader java.net.URLClassLoader @378fd1ac)
	at com.google.gson.JsonObject.getAsJsonArray(JsonObject.java:182)
	at program.SRRHelper.updateUnits(SRRHelper.java:342)
	at program.SRRHelper.<init>(SRRHelper.java:37)
	at program.Run$2.run(Run.java:103)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by ProjectBots** [comment]
The bot doesn’t support playing as captain at the moment. But plans for the future were made
