### ISSUE TITLE
consistent unknown error

### ISSUE THREAD

**Issue by mystixa** [ProjectBots/StreamRaidersBot#57]
[player] [1] Run -> slotSequence: slot=1 err=unknown

[fatal] [2:32:22] [runerr] [player] [2] Run -> slotSequence: slot=2 err=unknown
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at run.BackEndHandler.updateCaps(BackEndHandler.java:328)
	at run.BackEndHandler.getCaps(BackEndHandler.java:381)
	at run.Run.switchCap(Run.java:1028)
	at run.Run.switchCap(Run.java:984)
	at run.Run.captain(Run.java:962)
	at run.Run.captain(Run.java:852)
	at run.Run.slotSequence(Run.java:349)
	at run.Run.access$9(Run.java:309)
	at run.Run$3$1.run(Run.java:259)
	at java.base/java.lang.Thread.run(Thread.java:833)
	
	Any hints on getting around this?
	Ive tried running as admin but no go. 
	I had this after trying the min upgrade and now after downloading the full version and originally used imported config but also tried just doing it new and resetting everything manually.

**Comment by mystixa** [comment]
hmmm I'm not sure if theres a setting I can adjust to stop having the problem completely. Went a while today just fine, and then the problem reappeared later on. 

Looks like a workaround for the moment is booting out the captains exhibiting the problem and manually choosing some others.

**Comment by ProjectBots** [comment]
fixed in [v7.2.0beta](https://github.com/ProjectBots/StreamRaidersBot/releases/tag/v7.2.0beta)
