### ISSUE TITLE
Constant errors one each slot.

### ISSUE THREAD

**Issue by delenca** [ProjectBots/StreamRaidersBot#67]
Started showing up 2 updates ago. Now placement basicly doesn't seem to work at all. Unsure what is causing it. Thought maybe banned but I can place fine by the Browser.

 Run -> slotSequence: slot=2 err=unknown
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.get(String)" because the return value of "com.google.gson.JsonObject.getAsJsonObject(String)" is null
	at program.ConfigsV2.getUnitInt(ConfigsV2.java:350)
	at run.Viewer.findPlace(Viewer.java:788)
	at run.Viewer.place(Viewer.java:696)
	at run.Viewer.doSlot(Viewer.java:476)
	at run.Viewer.lambda$0(Viewer.java:348)
	at run.Viewer.useViewerBackEnd(Viewer.java:88)
	at run.Viewer.slotSequence(Viewer.java:345)
	at run.Viewer.access$6(Viewer.java:330)
	at run.Viewer$3$1.run(Viewer.java:285)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ProjectBots** [comment]
see #68

**Comment by ProjectBots** [comment]
can you test if the error persists in the latest release

**Comment by delenca** [comment]
Not a single issue now.
